/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#484c4e",
        "outline-variant": "#c4c5d5",
        "surface-container": "#e6eeff",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#ffdf9f",
        "on-error": "#ffffff",
        "inverse-surface": "#233144",
        "surface-tint": "#3755c3",
        "secondary-fixed-dim": "#f9bd22",
        "surface-container-highest": "#d5e3fc",
        "on-surface": "#0d1c2e",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#444653",
        "surface": "#f8f9ff",
        "primary-container": "#1e40af",
        "tertiary-fixed": "#e0e3e5",
        "secondary": "#795900",
        "on-tertiary-fixed-variant": "#444749",
        "on-primary-fixed-variant": "#173bab",
        "surface-dim": "#ccdbf3",
        "on-primary-container": "#a8b8ff",
        "on-background": "#0d1c2e",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#5c4300",
        "outline": "#757684",
        "on-secondary-fixed": "#261a00",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-container-high": "#dce9ff",
        "secondary-container": "#ffc329",
        "primary-fixed": "#dde1ff",
        "tertiary": "#323537",
        "error": "#ba1a1a",
        "surface-variant": "#d5e3fc",
        "on-error-container": "#93000a",
        "on-secondary-container": "#6f5100",
        "on-tertiary-fixed": "#191c1e",
        "background": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed": "#001453",
        "primary": "#00288e",
        "primary-fixed-dim": "#b8c4ff",
        "on-tertiary-container": "#b9bcbe",
        "inverse-primary": "#b8c4ff",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "24px",
        "unit": "8px",
        "margin-mobile": "16px",
        "container-max": "1280px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
